---
lazygit_source_directory: "{{ dotfiles_source_root }}/lazygit"
lazygit_destination_directory: "{{ dotfiles_xdg_config_home }}/lazygit"
lazygit_executable: "{{ dotfiles_values.lazygit.executable }}"
...
