################################################################################
# macOS
################################################################################

# Integrates the title bar with the terminal background.
macos-titlebar-style = transparent

# Uses the X-Ray Ghostty icon in the Dock and app switcher.
macos-icon = xray

# Quits Ghostty after closing its last window.
quit-after-last-window-closed = true
