################################################################################
# Keybindings
################################################################################

# Navigates between splits using Vim-style directions.
keybind = cmd+alt+h=goto_split:left
keybind = cmd+alt+j=goto_split:down
keybind = cmd+alt+k=goto_split:up
keybind = cmd+alt+l=goto_split:right

# Resizes the focused split by 10 pixels.
keybind = cmd+ctrl+h=resize_split:left,10
keybind = cmd+ctrl+j=resize_split:down,10
keybind = cmd+ctrl+k=resize_split:up,10
keybind = cmd+ctrl+l=resize_split:right,10

# Maximizes or restores the focused split.
# Mirrors tmux's native "prefix + z" convention.
keybind = cmd+alt+z=toggle_split_zoom

# Gives all splits the same amount of space.
keybind = cmd+alt+e=equalize_splits
