---
- name: Validate Neovim configuration
  ansible.builtin.command:
    argv:
      - "{{ nvim_executable }}"
      - --headless
      - -i
      - NONE
      - -n
      - "+lua assert(vim.v.errmsg == '', vim.v.errmsg)"
      - "+qa"
  environment:
    XDG_CONFIG_HOME: "{{ dotfiles_xdg_config_home }}"
  changed_when: false
