---
- name: Configure macOS workstation
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - role: ghostty
      tags:
        - ghostty

    - role: nvim
      tags:
        - nvim

    - role: tmux
      tags:
        - tmux
