################################################################################
# tmux
################################################################################

# Carica i moduli di configurazione in orgine esplicito.
source-file -q ~/.config/tmux/conf.d/10-server.conf
source-file -q ~/.config/tmux/conf.d/20-terminal.conf
source-file -q ~/.config/tmux/conf.d/30-input.conf
source-file -q ~/.config/tmux/conf.d/40-sessions.conf
source-file -q ~/.config/tmux/conf.d/50-windows.conf
source-file -q ~/.config/tmux/conf.d/60-panes.conf
source-file -q ~/.config/tmux/conf.d/70-copy-mode.conf
source-file -q ~/.config/tmux/conf.d/80-status.conf
source-file -q ~/.config/tmux/conf.d/90-plugins.conf
