---
ghostty_source_template: "{{ dotfiles_source_root }}/ghostty/config.ghostty.j2"
ghostty_destination_directory: "{{ dotfiles_xdg_config_home }}/ghostty"
ghostty_executable: "{{ dotfiles_values.ghostty.executable }}"
...
