################################################################################
# Terminal
################################################################################

# Exposes modern terminal capabilities to tmux.
set -g default-terminal "tmux-256color"

# Enables True Color (24-bit) when supported by the terminal.
set -as terminal-feature ",xterm-ghostty:RGB"
