################################################################################
# Input
################################################################################

# Enables mouse support to:
# - select panes and windows
# - resize panes
# - scroll through history
set -g mouse on

# Retains the standard tmux prefix: Ctrl-b.
# It does not need to be set explicitly.
