################################################################################
# Status bar
################################################################################

# Nord theme for tmux.
#
# Preserves standard tmux behavior and primarily changes the status bar,
# colors and formatting.
run-shell "~/.config/tmux/themes/nord/nord.tmux"
